logging:
  level:
    org.springframework: ERROR
    com.mkyong: DEBUG

spring:
  profiles:
    active: dev
#  main:
#    banner-mode: off

email: kripesh@yaml.com
thread-pool: 10

business:
  menus:
    - title: Home
      name: Home
      path: /
    - title: Contact
      name: Contact
      path: /contact
  themes:
    default-folder: /assets/themes/kripesh
  servers:
    - ip: 127.0.0.1
      path: /dev1
    - ip: 127.0.0.2
      path: /dev2
    - ip: 127.0.0.3
      path: /dev3